version: '3.9'

networks:
  shared-net:
    driver: bridge

volumes:
  mongo-data:
  # prometheus-data:   # commented
  # grafana-data:      # commented
  qdrant-data:
  minio-data:

services:
  mongo:
    image: mongo:6
    container_name: mongo
    networks:
      - shared-net
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${SHARED_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${SHARED_PASS}
      - MONGO_INITDB_DATABASE=admin
    command: ["mongod", "--auth"]   # enforce authentication
    ports:
      - "27017:27017"
    restart: on-failure

  vector-db:
    image: qdrant/qdrant:v1.12.3
    container_name: vector-db
    networks:
      - shared-net
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant-data:/qdrant/storage

  # prometheus:
  #   image: prom/prometheus:v3.5.0
  #   container_name: prometheus
  #   networks:
  #     - shared-net
  #   volumes:
  #     - prometheus-data:/prometheus
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana:12.2.0-16952534486-ubuntu
  #   container_name: grafana
  #   networks:
  #     - shared-net
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${SHARED_NAME}
  #     - GF_SECURITY_ADMIN_PASSWORD=${SHARED_PASS}
  #   ports:
  #     - "9080:9080"

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    networks:
      - shared-net
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${SHARED_NAME}
      - MINIO_ROOT_PASSWORD=${SHARED_PASS}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
