version: '3.9'

networks:
  shared-net:
    driver: bridge

volumes:
  mongo-data:
  prometheus-data:
  grafana-data:

services:
  mongo:
    image: mongo:6
    container_name: mongo
    networks:
      - shared-net
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  vector-db:
    image: milvusdb/milvus:2.3.0
    container_name: vector-db
    networks:
      - shared-net
    ports:
      - "19530:19530"

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    networks:
      - shared-net
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.2.0-16952534486-ubuntu
    container_name: grafana
    networks:
      - shared-net
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${SHARED_NAME}
      - GF_SECURITY_ADMIN_PASSWORD=${SHARED_PASS}
    ports:
      - "9080:9080"
