name: Deploy Shared Services

on:
  push:
    branches:
      - main
    paths:
      - 'shared-services.yml'
      - '.github/workflows/shared-services-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log env
        run: |
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Username: ${{ secrets.VPS_USERNAME }}"
          echo "Key starts with: $(echo "${{ secrets.VPS_PRIVATE_KEY }}" | head -c 20)..."


      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            mkdir -p /shared-dev
            cd /shared-dev
            if [ ! -d "multi-team-dev-deployment/.git" ]; then
              rm -rf multi-team-dev-deployment
              git clone https://github.com/IliaFarzi/multi-team-dev-deployment.git multi-team-dev-deployment
            fi
            cd multi-team-dev-deployment
            echo "SHARED_NAME=${{ secrets.SHARED_NAME }}" > .shared.env
            echo "SHARED_PASS=${{ secrets.SHARED_PASS }}" >> .shared.env
            git pull origin main
            docker compose -f shared-services.yml --env-file .shared.env pull
            docker compose -f shared-services.yml --env-file .shared.env up -d --no-build
